# Generated by Django 2.2.6 on 2020-10-08 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='Trainer',
        ),
    ]
